version: '3'
services:
    chart-server:
        image: chart-server
        restart: always
        environment:
            # 环境变量=后面一定不要有空格
            - SERVICE_9421_NAME=chart-server
        ports:
            - "9421"
        deploy:
            resources:
                limits:
                    cpus: '0.2'
                    memory: 200M
                reservations:
                    cpus: '0.1'
                    memory: 100M
        ports:
          - "9421:9421"
