version: '3'
services:
    httpsserver:
        image: httpsserver
        restart: always
        environment:
            # 环境变量=后面一定不要有空格
            - SERVICE_80_NAME=httpserver
        ports:
            - "9420"
